import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import YAML from 'yaml';
import { describe, expect, it } from 'vitest';

import { detectDistress, isStopRequest, safetyConfigSchema } from '../rules';

const config = safetyConfigSchema.parse(
  YAML.parse(readFileSync(join(__dirname, '../../../data/safety.yaml'), 'utf8')),
);

describe('isStopRequest', () => {
  it.each([
    'stop',
    'Stop.',
    'pause',
    'Please stop.',
    'Can we stop?',
    "Let's pause here.",
    'I want to stop the roleplay',
    'ok stop now',
    'No, stop.',
    'Wait, stop.',
    'Stop it.',
    'Stop it!',
    'Please stop it.',
    'Just stop it.',
    'Stop this.',
    'Stop this, please.',
    'Can we stop it?',
    'Can we stop this?',
    'Stop it now.',
    // Round 6 probes.
    'Sam, stop.',
    'Stop it, Sam.',
    'Jordan, please stop.',
    'Stop that.',
    'stop pls',
    'Sorry, I need to stop the practice now.',
    'Can we please stop the roleplay now, please?',
    'Please stop now, I mean it.',
    'Stop. I can’t do this, I feel sick.',
    "OK, let's stop there.",
    'Could we stop for a moment?',
    // Round 7 probes (D-063).
    'No, no, no, stop.',
    'Stop, stop, stop, stop.',
    'Hold on, stop.',
    'Hang on, can we stop?',
    'Enough, stop.',
    'OK stop, this is too much.',
    'Stop, Sam, please.',
    'Please, Sam, stop.',
    'Stop, Jordan, please.',
    "Stop, I can't do this.",
    "Stop, I can't do this, I feel sick.",
    'Stop, thank you.',
    // Round 9 probes (D-072): frightened and plain stops must always stop.
    "Stop, I can't do this anymore.",
    "Stop, I'm scared.",
    "Stop, please, I'm scared.",
    "Stop, you're scaring me.",
    "Stop, I'm not okay.",
    "Stop, I don't want to do this.",
    'Stop, this is too much for me.',
    "Stop, stop, I can't handle this.",
    'Stop, I need to take a break.',
    "Stop, I'm done.",
    "Stop, that's enough.",
    "Can we stop, I'm not feeling well?",
    "I'm sorry, I need to stop.",
    "I'm sorry, can we stop?",
    "Please, I'm begging you, stop.",
    'I said, stop.',
    'Seriously, stop.',
    'Honestly, can we stop?',
    'Oh god, stop.',
    'Yeah, I want to stop.',
    "Yes, let's stop.",
    'Um, can we stop?',
  ])('stops on %j', (line) => expect(isStopRequest(line, config, ['Sam', 'Jordan', 'Alex'])).toBe(true));

  it('treats the persona’s name, including a two-word custom name, as addressing them', () => {
    expect(isStopRequest('Alex stop', config, ['Alex'])).toBe(true);
    expect(isStopRequest('Alex stop', config)).toBe(false);
    expect(isStopRequest('Dana Smith, stop.', config, ['Dana Smith'])).toBe(true);
  });

  it.each([
    'Stop blocking the release.',
    'No, stop adding scope.',
    'Can we pause it?',
    'Can we pause this?',
    'I need this to stop.',
    'We need to stop adding scope mid-sprint.',
    "Don't stop now, we're close.",
    'Can we pause the migration until billing ships?',
    'The deadline is Friday.',
    '',
    'Stop blocking the release, Sam.',
    'Sam, stop adding scope.',
    'Can we stop the export?',
    "Let's pause and think about the plan.",
    // Round 7 probes (D-064): interrupting the persona is roleplay, not a stop.
    'Can I stop you there?',
    'Sorry, can I stop you there? The release is Friday.',
    'Can I just stop you for a second?',
    "I'd like to stop you there.",
    'Wait, can I stop you there, Sam?',
    // Round 8 probes (D-067): a comma after a pause opener is still pushback.
    "Can we pause, and look at what's already in the sprint?",
    "I'd like to pause, and think about my current load.",
    'We need to pause, the release is blocked.',
    "Let's pause, and look at the numbers.",
    'I want to pause, not cancel it.',
    'Sam, can we pause, I need to talk about the release.',
    "OK, let's pause, what's actually blocking the merge?",
    'Hang on, let’s pause, you said QA signed off?',
  ])('keeps the roleplay going on %j', (line) => expect(isStopRequest(line, config, ['Sam'])).toBe(false));
});

// Every line below came from a review round that caught the filter getting it wrong.
describe('detectDistress', () => {
  it.each([
    'Honestly I want to kill myself when this happens.',
    "I don't want to be alive anymore.",
    'I have been thinking about suicide.',
    "I think I'm having a panic attack.",
    'My manager grabbed me last week.',
    'I’d be better off dead.',
    "I've been cutting myself again.",
    'Sometimes I think about hurting myself.',
    "I've been cutting myself for weeks and I can't stop.",
    'I keep hurting myself and nobody knows.',
    'I keep thinking about hurting myself tomorrow.',
    'I want to hurt myself so badly right now.',
    "I've been harming myself since the reorg.",
    'My manager hit me on the arm in the meeting.',
    'Sam hit me.',
    "I've thought about killing myself.",
    'He touched me without asking.',
    'I want to kill myself for real this time.',
    "I'm going to kill myself on Friday.",
    "I'm going to kill myself at the weekend.",
    'I want to kill myself with the pills in my drawer.',
    "I'm planning to kill myself over the weekend.",
    'I just hurt myself again last night.',
    'I only hurt myself when it gets this bad.',
    'My manager hit me last week.',
    'He hit me when I said no.',
    'He hit me hard across the face.',
    'I want to hurt myself by taking all my pills.',
    'I keep hurting myself and my arms are covered in scars.',
    'He hit me with a stapler.',
    'My boss keeps hitting me.',
    "I've been thinking about ending it all.",
    'I want to take my own life.',
    // Builder's own probes of the idiom exceptions.
    "I'm hurting myself.",
    "I'm just hurting myself more and more.",
    'He threw a stapler and it hit me.',
    'He threw it at me and it hit me in the face.',
    "I'm thinking of killing myself tonight.",
    'i wanna kill myself',
    "I've been self-harming.",
    'My lead slapped me.',
    'I cut myself off from everyone and I want to die.',
    // Round 6 probes (D-055): disclosures that an idiom must never cancel.
    "I've been thinking about killing myself to make it all stop.",
    'Some nights I think about killing myself to get away from all this.',
    'I keep thinking about killing myself over the project.',
    'I thought about killing myself here in the office last week.',
    'The guy that grabbed me in the lift is my team lead.',
    'My manager hit me back when I pushed his hand away.',
    'What hit me was his fist.',
    'He threw his mug at me and it hit me hard.',
    'The manager that touched me is still on my team.',
    'The colleague that hit me last week is in this meeting.',
    "I'm just hurting myself, every single night.",
    'Hit me up on Slack, he hit me yesterday.',
    "I'm killing myself with pills.",
    // Round 6 probes (D-056): phrasings never caught before.
    'I wanna die.',
    "I don't wanna be alive anymore.",
    'I wish I was dead.',
    'I want to be dead.',
    "I'm going to hang myself tonight.",
    'I almost killed myself last year.',
    'I harmed myself again last night.',
    "I'm going to take all my pills after this call.",
    "I'm going to jump off the roof after this meeting.",
    'Everyone would be better off without me.',
    'I do not want to live anymore.',
    'I cannot breathe.',
    "I'm about to have a panic attack.",
    'He hurt me.',
    'My manager keeps touching me.',
    'He pushed me into the wall.',
    "I'm being sexually harassed by my manager.",
    'I was sexually assaulted at the offsite.',
    'He raped me.',
    'I want to kill my self.',
    'I want to kill  myself.',
    'I want to kill\nmyself.',
    // Builder's round 6 probes.
    "I want to end things.",
    "Sometimes I just want to disappear forever.",
    "I feel like dying.",
    "I don't see the point in living anymore.",
    "I've been having panic attacks every day.",
    "I'm planning to end it.",
    "I've started cutting myself again.",
    "I tried to kill myself in March.",
    "He grabbed me by the arm.",
    "I'm scared to go home because he hits me.",
    // Round 7 probes (D-061): an idiom must never cover a disclosure.
    "I'm killing myself on Friday.",
    "I'm killing myself for real this time.",
    "I'm killing myself over the weekend.",
    "I'm killing myself to end this.",
    "I'm killing myself over this, I have a plan.",
    "That man touched me.",
    "That guy in finance touched me.",
    "This man at work touched me.",
    "It was Sam who touched me.",
    "The meeting ended and he hit me.",
    "The call ended and he hit me.",
    "He threw a stapler at me, and it hit me in the head.",
    "Honestly, it hit me in the face.",
    "I dont want to live anymore.",
    "I cant breathe.",
    "He pushed me to the ground.",
    "My manager pushed me to the floor in the car park.",
    "I'm killing myself here, I have the pills in my desk.",
    "What grabbed me was his hand on my neck.",
    "I slit my wrists last night.",
    "I'm going to jump in front of a train.",
    // Builder's round 7 probes.
    "I got hit by my manager.",
    "I'm thinking of ending it.",
    "He hit me again last night.",
    "She keeps touching me at work.",
    "I tried to hang myself.",
    "I'm cutting myself, I can't stop.",
    // Round 8 probes (D-066): disclosures a narrowing commit lost. Tier 1 only ever grows.
    "He tried to rape me.",
    "He tried to rape me at the offsite.",
    "My manager tried to rape me.",
    "I'm a rape survivor.",
    "I was the victim of a sexual assault.",
    "There was a sexual assault at the offsite and it was me.",
    "I'm dealing with sexual harassment from my manager.",
    "I've been getting sexually harassed at work.",
    "I keep being sexually harassed by my team lead.",
    "My husband beats me.",
    "He beats me when he's drunk.",
    "My manager beats me.",
    "He grabbed my wrist and it hurt me.",
    "He twisted my arm and it really hurt me.",
    "My manager hit me back after I pushed his hand away.",
    "He hit me back after I slapped him.",
    "He hit me back today.",
    "He picked up the stapler and hit me with it.",
    "He threw his phone at me and hit me with it.",
    "He hit me up against the wall.",
    "He grabbed a chair and that hit me hard.",
    "I don't see the point in going on, honestly.",
    "I don't see any point in going on with my life.",
    "There's no point in going on like this, I want out.",
    "What's the point of going on, really?",
    "I'm literally having a panic attack.",
    "Sorry, I'm actually having a panic attack.",
    "I can feel myself having a panic attack.",
    "He attacked me in the car park.",
    "I was attacked on the way home.",
    "I got punched by a customer.",
    "I was groped by a client at the conference.",
    "He slapped my face.",
    "He tried to molest me.",
    "I had a panic attack in the bathroom.",
    "I'm starting to have a panic attack.",
    // Round 9 probes (D-070): carve-outs must never be next-word tests.
    "He kicked me outside the pub.",
    "He kicked me off my bike.",
    "He kicked me off my chair.",
    "The guy in finance kicked me off the stairs.",
    "He kicked me out of bed and kept kicking.",
    "He shoved me into the meeting room wall.",
    "He shoved me into a meeting room and locked the door.",
    "He shoved me into the team room and slammed the door.",
    "My dad beat me at the weekend.",
    "He beat me at home again last night.",
    "He beat me by the bins behind the office.",
    "She beat me by the car.",
    "My husband beats me at home.",
    "He beats me at least once a week.",
    // Round 9 probes (D-071): the harm in one sentence, the idiom in the next.
    "He threw a stapler at me. It really hurt me.",
    "He squeezed my hand, it really hurt me.",
    "He pulled my hair. It hurt me.",
    "He threw his coffee at me, that really hurt me.",
    "He picked up the stapler, hit me with it.",
    "He picked up the stapler. Hit me with it.",
    "He shoved the desk, that hit me hard.",
    "He threw a mug at me. That hit me hard.",
    "He lost his temper. Hit me up the back of the head.",
    "I feel like killing myself to get this project over with.",
    "I'm seriously considering killing myself to get the work done with.",
    "I keep imagining killing myself to finish the project.",
    "My manager pushed me into agreeing to sleep with him.",
    // D-056 phrasings never caught before round 9.
    "I've been cutting my wrists.",
    "I'm going to step in front of a bus.",
    "I want to unalive myself.",
    "I'm going to kms.",
    "I'm going to off myself.",
    "I'm going to end it tonight.",
    "I wanted to die last night.",
    "I wish I could die.",
    "I'd rather be dead.",
    "I don't want to wake up tomorrow.",
    "I took a bunch of pills last night.",
    "He threatened to kill me.",
    "He pinned me against the wall.",
    // Builder's round 9 probes.
    "Nobody would care if I disappeared.",
    "Hit me up on Slack when it merges, he hit me yesterday.",
    "Can you hit me back? He hit me last week.",
    "The layoffs hit me hard and I've been cutting myself.",
    "Honestly, I'd just be hurting myself. I already hurt myself last night.",
    "He keeps grabbing me in the lift.",
    "I'm being hurt at home.",
    "I was hit on the way to work.",
  ])('flags %j', (line) => expect(detectDistress(line, config)).toBe(true));

  it.each([
    'This deadline is killing me.',
    "I'd kill for one quiet sprint.",
    "I'm dying to ship this.",
    "I'm not okay with adding scope on day six.",
    'That PR is dead in the water until security signs off.',
    'We need to hit Friday.',
    'Hit me up on Slack when it merges.',
    "I'd be hurting myself and the team's delivery if I took it on.",
    'I need to cut myself some slack this sprint.',
    "I'm killing myself to hit this deadline.",
    'They hit me with a new requirement on day six.',
    'I wanted to die of embarrassment in that demo.',
    "Honestly, I'd just be hurting myself.",
    "If I say yes to this too, I'm only hurting myself.",
    'That news hit me hard.',
    'What you said in the retro really touched me.',
    'Can you hit me back after standup?',
    'The layoffs hit me too.',
    'Honestly, your message touched me.',
    'What grabbed me about your proposal was the timeline.',
    'I cut myself off from the planning thread.',
    "I'm killing myself here.",
    // Round 6 probes (D-057).
    "I've been killing myself for this team for two years.",
    "I'm already killing myself on the migration.",
    "I'm killing myself trying to hit Friday.",
    "I'm killing myself with overtime already.",
    'Hit me on Slack when it merges.',
    'Go on, hit me with your feedback.',
    'Just hit me with it.',
    'The deadline change hit me like a truck.',
    'It touched me that you noticed.',
    'Saying yes would hurt myself and the team.',
    'That comment really hurt me.',
    'Alex pushed me to take it on.',
    'That deadline really hurt me.',
    'I want to end things with this vendor.',
    'Honestly, that really hit me hard.',
    'Sales pushed me into taking the call.',
    "I'm cutting myself some slack today.",
    // Round 7 probes (D-062).
    "I don't want to shoot myself in the foot by saying yes.",
    "I'm trying to cut myself some slack this sprint.",
    "I'm going to cut myself some slack.",
    'I want to cut myself a break.',
    'I still have my sexual harassment training due this week.',
    "What's the point of going on with the review if nothing merges?",
    "Honestly, I'd be killing myself to hit that date.",
    'Dana hit me with a new requirement.',
    'You beat me to it.',
    'Sam beat me to it, he already merged the fix.',
    'Taking this on on top of billing is a suicide mission.',
    'Can you hit me back?',
    'Sales pushed me to agree to Thursday.',
    // Round 8 probes (D-068) that a closed idiom now covers.
    "If I take this on, I'd be hurting myself and my team.",
    "I'm killing myself to get the release out.",
    'He pushed me to finish it by Friday.',
    'I need to cut myself off from Slack after six.',
    'Hit me back by EOD.',
    'That feedback really hurt me.',
    'Alex beat me to the punch.',
    'That idea really grabbed me.',
    'Your comment in standup hit me hard.',
    "I've been killing myself on this for weeks.",
    "I'm killing myself trying to get this done.",
    'I got hit by a wall of emails this morning.',
    // Round 9 probes (D-073): status lines and scenario premises.
    'I got hit with a new requirement on day six.',
    'I got hit with three bug reports from QA this morning.',
    "I'm being pushed to take this on.",
    "I've been pushed by QA all week about this.",
  ])('does not flag the workplace idiom %j', (line) => expect(detectDistress(line, config)).toBe(false));
});

// Lines that pause the practice even though they are workplace idioms. Each one shares its exact
// wording with a real disclosure ("… and it hit me hard"), so the filter accepts the pause.
describe('accepted false stops', () => {
  it.each(["No, stop, that's not what I said."])('stops on %j, because a bare "stop" always stops', (line) =>
    expect(isStopRequest(line, config, ['Sam'])).toBe(true),
  );
});

describe('accepted false positives', () => {
  it.each([
    'That touched me.',
    'It hit me hard.',
    'This scope change pushed me to the limit.',
    'QA is having a panic attack about Friday.',
    'Alex is going to have a panic attack when he sees the burndown.',
    // Idioms that no whole-line template covers, so they pause the practice.
    'It hit me last night that we never scoped it.',
    'It hit me that we forgot QA.',
    'It really hit me when you said that.',
    'The VPN kicked me off the call.',
    'Zoom kicked me out of the meeting twice.',
    'They shoved me onto the on-call rota.',
    'You beat me by a day.',
    'Jenkins kicked me out.',
    'They shoved me onto another project.',
    'Beats me why the build failed.',
    "Sam, hit me back once you've looked.",
  ])(
    'pauses on %j',
    (line) => expect(detectDistress(line, config)).toBe(true),
  );
});

// Generated, not hand-picked: every idiom that covers a harm word must stop covering it the
// moment a person is the one doing it. This is the test that would have caught rounds 4-8.
describe('idioms never cover a person doing the harm', () => {
  const idioms = [
    'hit me back', 'hit me up', 'hit me with it', 'hit me hard', 'hit me', 'hurt me', 'really hurt me',
    'touched me', 'really touched me', 'grabbed me', 'pushed me', 'beat me', 'kicked me', 'shoved me',
  ];
  const people = ['He', 'She', 'My manager', 'My husband', 'The guy in finance', 'Sam'];
  const endings = ['.', ' today.', ' after I pushed him away.', ' last night.', ' against the wall.'];
  const lines = people.flatMap((person) => idioms.flatMap((idiom) => endings.map((end) => `${person} ${idiom}${end}`)));
  const consequences = ['He grabbed my arm and it hurt me.', 'He threw a mug and it hit me.', 'He shoved the desk and that hit me hard.'];
  // The harm in one sentence or clause, an idiom-shaped line in the next.
  const harm = ['He threw a stapler at me', 'He grabbed my arm', 'He lost his temper', 'My manager cornered me'];
  const idiomLines = ['it really hurt me', 'that hit me hard', 'hit me with it', 'hit me up the back of the head', 'it touched me', "I'm only hurting myself"];
  const split = harm.flatMap((h) => idiomLines.flatMap((i) => [`${h}. ${i[0]!.toUpperCase()}${i.slice(1)}.`, `${h}, ${i}.`]));

  it.each([...lines, ...consequences, ...split])('flags %j', (line) => expect(detectDistress(line, config)).toBe(true));
});

describe('data/safety.yaml', () => {
  it('ships a disclaimer and crisis resources with links', () => {
    expect(config.disclaimer).toMatch(/not therapy/);
    expect(config.resources.filter((resource) => resource.url).length).toBeGreaterThanOrEqual(3);
  });
});
